/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Manifest file declaring the widget types provided by a framework-core-ui plugin.
 */
export interface SctManifest {
  $schema?: "https://app-framework/schemas/sct-manifest.json";
  /**
   * Manifest format version.
   */
  version: string;
  /**
   * List of widget definitions provided by this plugin.
   */
  widgets: SctWidgetEntry[];
}
/**
 * A single widget entry in the manifest.
 */
export interface SctWidgetEntry {
  /**
   * Unique widget identifier used as the registry key.
   */
  name: string;
  /**
   * Human-readable description of the widget's purpose.
   */
  description: string;
  /**
   * Glob pattern matched against EventBus channel names to determine whether this widget can handle a given event stream.
   */
  channelPattern: string;
  /**
   * List of MIME types that this widget expects to receive. Used for capability-based layout resolution.
   */
  consumes: string[];
  /**
   * Priority used to break ties when multiple widgets match the same channel. Higher values win.
   */
  priority?: number;
  /**
   * Optional preferred region where this widget should be placed by default.
   */
  defaultRegion?: string;
  /**
   * JSON Schema-compatible map of configurable parameter names to their schema descriptors.
   */
  parameters?: {
    /**
     * JSON Schema descriptor for a single parameter.
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
  /**
   * Relative import path resolved from the manifest file's location. Always starts with './'.
   */
  module: string;
  /**
   * Named export in the module that holds the React component.
   */
  export: string;
  [k: string]: unknown;
}
